# Documentation/specs available here: https://github.com/apache/infrastructure-asfyaml
github:
  enabled_merge_buttons:
    squash: true
    squash_commit_message: PR_TITLE
    merge: false
    rebase: false