################################################################################
#
#    Licensed to the Apache Software Foundation (ASF) under one or more
#    contributor license agreements.  See the NOTICE file distributed with
#    this work for additional information regarding copyright ownership.
#    The ASF licenses this file to You under the Apache License, Version 2.0
#    (the "License"); you may not use this file except in compliance with
#    the License.  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#
################################################################################
# Karaf log triage for archive-it-run.sh (supports log4j2 rollover: karaf.log, karaf.log.1, …).
# Expects archive hooks: target_path, staging_path, log_staged_file, register_staged_file,
# mark_included, ui_spinner_run, ui_detail, line_matches_expected_pattern, PATTERNS_FILE,
# TARGET_DIR, FULL_KARAF, MANIFEST.

KARAF_PRIMARY_LOG="karaf.log"
KARAF_TAIL_MAX_LINES=20000
KARAF_MATCH_CONTEXT_BEFORE=15
KARAF_MATCH_CONTEXT_AFTER=15
KARAF_STACK_MAX_LINES=120
KARAF_TRIGGER_RE='ERROR|WARN |Exception|Caused by:|<<< FAILURE|<<< ERROR|FATAL'
KARAF_BLOCK_HEADER_RE='^--- block [0-9]+ \(lines [0-9]+-[0-9]+'
KARAF_CORRELATION_HEADER_RE='^--- correlated with '
KARAF_RECENT_LOG="karaf-recent.log"
KARAF_SEGMENTS_INDEX="karaf-log-segments.txt"
KARAF_ERRORS_LOG="karaf-errors-warnings.log"
KARAF_UNEXPECTED_LOG="karaf-unexpected-candidates.log"
KARAF_FAILURE_CORRELATION_LOG="karaf-failure-correlation.log"
KARAF_TRIAGE_SUMMARY="karaf-triage-summary.txt"
KARAF_EXCEPTION_INDEX="karaf-exception-index.tsv"
KARAF_FAILED_TESTS_REL="${FAILED_TESTS_REL:-failed-tests.txt}"
KARAF_IT_SOURCES="src/test/java/org/apache/unomi/itests"
KARAF_PATTERNS_REL="expected-karaf-log-patterns.txt"
KARAF_STATIC_DUMMY_PATTERNS=(
    dummy_scope
    'event type: dummy'
    'eventType":"dummy'
    dummy_workspace
)

karaf_write_log_checker_patterns() {
    if [ ! -d "$KARAF_IT_SOURCES" ]; then
        return
    fi
    grep -rh 'addIgnoredSubstring' "$KARAF_IT_SOURCES" --include='*IT.java' 2>/dev/null \
        | sed -n 's/.*addIgnoredSubstring("\([^"]*\)").*/SUBSTRING: \1/p' \
        | sort -u
    grep -rh 'addIgnoredMultiPart' "$KARAF_IT_SOURCES" --include='*IT.java' 2>/dev/null \
        | sed -n 's/.*addIgnoredMultiPart(\(.*\)).*/\1/p' \
        | sed 's/", "/|/g; s/"//g' \
        | sed 's/^/MULTIPART: /' \
        | sort -u
}

generate_expected_patterns() {
    {
        echo "# Expected Karaf log patterns for LLM triage"
        echo "# Generated by archive-it-run.sh from LogChecker.createLogChecker() in *IT.java"
        echo "# SUBSTRING: ignore log lines containing this text (intentional failure/hardening tests)"
        echo "# MULTIPART: ignore if all pipe-separated parts appear on the same line in order"
        echo
        echo "# Static fixtures (dummy schema/scope tests — not production errors)"
        local pattern
        for pattern in "${KARAF_STATIC_DUMMY_PATTERNS[@]}"; do
            echo "SUBSTRING: $pattern"
        done
        echo
        karaf_write_log_checker_patterns
    } > "$PATTERNS_FILE"
    log_staged_file "$KARAF_PATTERNS_REL" "Generated $KARAF_PATTERNS_REL"
    mark_included
}

line_matches_expected_pattern() {
    local line="$1"
    local pattern_line needle rest part
    line="$(karaf_strip_ansi "$line")"
    while IFS= read -r pattern_line || [ -n "$pattern_line" ]; do
        case "$pattern_line" in
            ''|\#*) continue ;;
            SUBSTRING:*)
                needle="${pattern_line#SUBSTRING: }"
                if [[ "$line" == *"$needle"* ]]; then
                    return 0
                fi
                ;;
            MULTIPART:*)
                rest="$line"
                IFS='|' read -ra multipart <<< "${pattern_line#MULTIPART: }"
                for part in "${multipart[@]}"; do
                    if [[ "$rest" != *"$part"* ]]; then
                        continue 2
                    fi
                    rest="${rest#*"$part"}"
                done
                return 0
                ;;
        esac
    done < "$PATTERNS_FILE"
    return 1
}

karaf_staged_path() {
    staging_path "$1/$2"
}

karaf_log_dir_has_segments() {
    local log_dir="$1"
    [ -f "$log_dir/$KARAF_PRIMARY_LOG" ] || compgen -G "$log_dir/$KARAF_PRIMARY_LOG.[0-9]*" >/dev/null
}

list_karaf_log_segments() {
    local log_dir="$1"
    local max_i=0 i f

    shopt -s nullglob
    for f in "$log_dir"/"$KARAF_PRIMARY_LOG".[0-9]*; do
        [ -f "$f" ] || continue
        i="${f##*.}"
        [[ "$i" =~ ^[0-9]+$ ]] || continue
        if [ "$i" -gt "$max_i" ]; then
            max_i="$i"
        fi
    done
    shopt -u nullglob

    while [ "$max_i" -gt 0 ]; do
        f="$log_dir/$KARAF_PRIMARY_LOG.$max_i"
        if [ -f "$f" ]; then
            printf '%s\n' "$f"
        fi
        max_i=$((max_i - 1))
    done

    if [ -f "$log_dir/$KARAF_PRIMARY_LOG" ]; then
        printf '%s\n' "$log_dir/$KARAF_PRIMARY_LOG"
    fi
}

count_karaf_log_segments() {
    list_karaf_log_segments "$1" | wc -l | tr -d ' '
}

merge_karaf_log_segments() {
    local log_dir="$1"
    local out="$2"
    local seg

    : > "$out"
    while IFS= read -r seg; do
        [ -n "$seg" ] || continue
        cat "$seg" >> "$out"
    done < <(list_karaf_log_segments "$log_dir")
}

write_karaf_segments_index() {
    local log_dir="$1"
    local base_dir="$2"
    local out order=0
    local seg name bytes

    out="$(karaf_staged_path "$base_dir" "$KARAF_SEGMENTS_INDEX")"
    {
        echo "# Karaf log segments in chronological order (oldest first)"
        echo "# Rolled files: karaf.log.N (higher N = older); active file: karaf.log"
        echo "# order\tfile\tbytes"
        while IFS= read -r seg; do
            [ -n "$seg" ] || continue
            order=$((order + 1))
            name="$(basename "$seg")"
            bytes="$(wc -c < "$seg" 2>/dev/null | tr -d ' ')"
            printf '%d\t%s\t%s\n' "$order" "$name" "$bytes"
        done < <(list_karaf_log_segments "$log_dir")
    } > "$out"
    register_staged_file "$base_dir/$KARAF_SEGMENTS_INDEX" \
        "Added Karaf rollover segment index from $log_dir"
}

karaf_segment_summary() {
    local count="$1"
    local rollover_count=$((count - 1))
    local summary="karaf.log"

    if [ "$rollover_count" -gt 0 ]; then
        summary="$summary + $rollover_count rollover segment(s)"
    fi
    printf '%s' "$summary"
}

karaf_strip_ansi() {
    sed $'s/\033\\[[0-9;]*m//g' <<< "$1"
}

karaf_is_trigger_line() {
    [[ "$1" =~ $KARAF_TRIGGER_RE ]] && return 0
    [[ "$1" =~ ^[a-zA-Z0-9_.$]+(\.[a-zA-Z0-9_$]+)*(Exception|Error): ]] && return 0
    return 1
}

karaf_is_globally_ignored_line() {
    # LogChecker fast path: BundleWatcher startup warnings are expected churn.
    [[ "$1" =~ \|[^|]*WARN[^|]*\|[^|]*BundleWatcher ]] && return 0
    [[ "$1" == *"Old style feature file without namespace"* ]] && return 0
    return 1
}

karaf_line_is_actionable_trigger() {
    local stripped
    stripped="$(karaf_strip_ansi "$1")"
    karaf_is_trigger_line "$stripped" || return 1
    karaf_is_globally_ignored_line "$stripped" && return 1
    line_matches_expected_pattern "$stripped" && return 1
    return 0
}

is_karaf_block_header() {
    [[ "$1" =~ $KARAF_BLOCK_HEADER_RE ]] || [[ "$1" =~ $KARAF_CORRELATION_HEADER_RE ]]
}

write_karaf_recent_excerpt() {
    local merged="$1"
    local dest="$2"
    local total

    total="$(wc -l < "$merged" | tr -d ' ')"
    if [ "$total" -le "$KARAF_TAIL_MAX_LINES" ]; then
        cp "$merged" "$dest"
        return
    fi
    tail -n "$KARAF_TAIL_MAX_LINES" "$merged" > "$dest"
}

extract_karaf_errors_with_context() {
    local log="$1"
    local out="$2"
    awk -v before="$KARAF_MATCH_CONTEXT_BEFORE" \
        -v after="$KARAF_MATCH_CONTEXT_AFTER" \
        -v stack_max="$KARAF_STACK_MAX_LINES" \
        -v trigger_re="$KARAF_TRIGGER_RE" '
    function strip_ansi(s, t) {
        t = s
        while (match(t, /\033\[[0-9;]*m/)) {
            t = substr(t, 1, RSTART - 1) substr(t, RSTART + RLENGTH)
        }
        gsub(/\r/, "", t)
        return t
    }
    function is_timestamped_log(line) {
        return line ~ /^[0-9]{4}-[0-9]{2}-[0-9]{2}T/ \
            || line ~ /^[A-Z][a-z]{2} [0-9]{2}, [0-9]{4}/
    }
    function is_stack_line(line) {
        return line ~ /^[[:space:]]+at / \
            || line ~ /^Caused by:/ \
            || line ~ /^[[:space:]]+\.\.\. [0-9]+ more/
    }
    function is_exception_head(line) {
        return line ~ /^[a-zA-Z0-9_.$]+(\.[a-zA-Z0-9_$]+)*(Exception|Error):/
    }
    function is_globally_ignored(line,    s) {
        s = strip_ansi(line)
        if (s ~ /\|WARN[^|]*\|[^|]*BundleWatcher/) return 1
        if (index(s, "Old style feature file without namespace") > 0) return 1
        return 0
    }
    function is_trigger(line,    s) {
        if (is_globally_ignored(line)) return 0
        s = strip_ansi(line)
        if (s ~ trigger_re) return 1
        if (is_exception_head(s)) return 1
        return 0
    }
    function extend_end_for_stack(start_line, end_line,    j, extended) {
        extended = 0
        for (j = start_line + 1; j <= total; j++) {
            if (is_stack_line(lines[j]) || is_exception_head(strip_ansi(lines[j]))) {
                if (j > end_line) end_line = j
                extended++
                if (extended >= stack_max) break
                continue
            }
            if (is_timestamped_log(strip_ansi(lines[j]))) {
                break
            }
        }
        return end_line
    }
    {
        lines[NR] = $0
        total = NR
    }
    END {
        tcount = 0
        for (i = 1; i <= total; i++) {
            if (!is_trigger(lines[i])) continue
            tcount++
            triggers[tcount] = i
        }

        rcount = 0
        for (ti = 1; ti <= tcount; ti++) {
            i = triggers[ti]
            start = i - before
            if (start < 1) start = 1
            end = i + after
            if (end > total) end = total
            end = extend_end_for_stack(i, end)
            rcount++
            range_start[rcount] = start
            range_end[rcount] = end
            range_anchor[rcount] = i
        }

        if (rcount == 0) exit

        # Sort ranges by start line (insertion sort — few ranges).
        for (i = 2; i <= rcount; i++) {
            j = i
            while (j > 1 && range_start[j] < range_start[j - 1]) {
                tmp = range_start[j]; range_start[j] = range_start[j - 1]; range_start[j - 1] = tmp
                tmp = range_end[j]; range_end[j] = range_end[j - 1]; range_end[j - 1] = tmp
                tmp = range_anchor[j]; range_anchor[j] = range_anchor[j - 1]; range_anchor[j - 1] = tmp
                j--
            }
        }

        mcount = 0
        for (i = 1; i <= rcount; i++) {
            if (mcount == 0) {
                mcount = 1
                merged_start[1] = range_start[i]
                merged_end[1] = range_end[i]
                continue
            }
            if (range_start[i] <= merged_end[mcount] + 2) {
                if (range_end[i] > merged_end[mcount]) {
                    merged_end[mcount] = range_end[i]
                }
            } else {
                mcount++
                merged_start[mcount] = range_start[i]
                merged_end[mcount] = range_end[i]
            }
        }

        for (bi = 1; bi <= mcount; bi++) {
            printf "--- block %d (lines %d-%d) ---\n", bi, merged_start[bi], merged_end[bi]
            for (j = merged_start[bi]; j <= merged_end[bi]; j++) {
                print strip_ansi(lines[j])
            }
            print ""
        }
    }' "$log" > "$out"
}

write_karaf_exception_index() {
    local log="$1"
    local out="$2"
    awk '
    function strip_ansi(s, t) {
        t = s
        while (match(t, /\033\[[0-9;]*m/)) {
            t = substr(t, 1, RSTART - 1) substr(t, RSTART + RLENGTH)
        }
        return t
    }
    function sample_key(line,    s) {
        s = strip_ansi(line)
        if (s ~ /^[a-zA-Z0-9_.$]+(\.[a-zA-Z0-9_$]+)*(Exception|Error):/) {
            return s
        }
        if (s ~ /\|ERROR\|/) {
            sub(/^[^|]*\|[^|]*\|[^|]*\|[^|]*\| /, "", s)
            if (length(s) > 160) s = substr(s, 1, 160) "..."
            return "ERROR: " s
        }
        if (s ~ /\|WARN /) {
            sub(/^[^|]*\|[^|]*\|[^|]*\|[^|]*\| /, "", s)
            if (length(s) > 160) s = substr(s, 1, 160) "..."
            return "WARN: " s
        }
        return ""
    }
    {
        key = sample_key($0)
        if (key == "") next
        count[key]++
        if (!(key in first_line)) {
            first_line[key] = NR
        }
    }
    END {
        n = 0
        for (key in count) {
            n++
            keys[n] = key
            vals[n] = count[key]
            lines[n] = first_line[key]
        }
        for (i = 1; i <= n; i++) {
            for (j = i + 1; j <= n; j++) {
                if (vals[j] > vals[i] \
                    || (vals[j] == vals[i] && lines[j] < lines[i])) {
                    tmp = keys[i]; keys[i] = keys[j]; keys[j] = tmp
                    tmp = vals[i]; vals[i] = vals[j]; vals[j] = tmp
                    tmp = lines[i]; lines[i] = lines[j]; lines[j] = tmp
                }
            }
        }
        print "rank\tcount\tfirst_line\tsample"
        limit = (n > 80) ? 80 : n
        for (i = 1; i <= limit; i++) {
            gsub(/\t/, " ", keys[i])
            printf "%d\t%d\t%d\t%s\n", i, vals[i], lines[i], keys[i]
        }
    }' "$log" > "$out"
}

write_karaf_failure_correlation() {
    local merged="$1"
    local failed_file="$2"
    local out="$3"

    if [ ! -s "$failed_file" ]; then
        return 1
    fi

    {
        echo "# Karaf excerpts near failing tests (class/method anchors in stack traces or messages)"
        echo "# Source: $KARAF_FAILED_TESTS_REL — pair with failsafe-reports/AllITs.txt stack traces"
        echo
    } > "$out"

    awk -v before="$KARAF_MATCH_CONTEXT_BEFORE" \
        -v after="$KARAF_MATCH_CONTEXT_AFTER" \
        -v stack_max="$KARAF_STACK_MAX_LINES" \
        -v failed_file="$failed_file" \
        -v max_per_test=3 '
    function strip_ansi(s, t) {
        t = s
        while (match(t, /\033\[[0-9;]*m/)) {
            t = substr(t, 1, RSTART - 1) substr(t, RSTART + RLENGTH)
        }
        gsub(/\r/, "", t)
        return t
    }
    function is_timestamped_log(line) {
        return line ~ /^[0-9]{4}-[0-9]{2}-[0-9]{2}T/ \
            || line ~ /^[A-Z][a-z]{2} [0-9]{2}, [0-9]{4}/
    }
    function is_stack_line(line) {
        return line ~ /^[[:space:]]+at / \
            || line ~ /^Caused by:/ \
            || line ~ /^[[:space:]]+\.\.\. [0-9]+ more/
    }
    function is_exception_head(line) {
        return line ~ /^[a-zA-Z0-9_.$]+(\.[a-zA-Z0-9_$]+)*(Exception|Error):/
    }
    function matches_test(line, class, method) {
        if (index(line, class)) return 1
        if (index(line, class ".java")) return 1
        if (index(line, class "." method)) return 1
        if (index(line, "at ") && index(line, class) && index(line, method)) return 1
        return 0
    }
    function extend_end(anchor, end,    j, extended) {
        extended = 0
        for (j = anchor + 1; j <= total; j++) {
            if (is_stack_line(lines[j]) || is_exception_head(strip_ansi(lines[j]))) {
                if (j > end) end = j
                extended++
                if (extended >= stack_max) break
                continue
            }
            if (is_timestamped_log(strip_ansi(lines[j]))) break
        }
        return end
    }
    function print_block(test, anchor,    start, end, j, key) {
        if (anchor < 1 || anchor > total) return
        key = test SUBSEP anchor
        if (key in printed) return
        printed[key] = 1
        per_test[test]++
        if (per_test[test] > max_per_test) return
        start = anchor - before
        if (start < 1) start = 1
        end = anchor + after
        if (end > total) end = total
        end = extend_end(anchor, end)
        printf "--- correlated with %s (anchor line %d, excerpt %d-%d) ---\n", test, anchor, start, end
        for (j = start; j <= end; j++) {
            print strip_ansi(lines[j])
        }
        print ""
    }
    BEGIN {
        while ((getline test < failed_file) > 0) {
            if (test == "") continue
            tcount++
            tests[tcount] = test
            split(test, parts, ".")
            methods[tcount] = parts[length(parts)]
            classes[tcount] = test
            sub(/\.[^.]+$/, "", classes[tcount])
        }
        close(failed_file)
    }
    {
        lines[NR] = $0
        total = NR
    }
    END {
        for (ti = 1; ti <= tcount; ti++) {
            test = tests[ti]
            class = classes[ti]
            method = methods[ti]
            per_test[test] = 0
            for (i = 1; i <= total; i++) {
                line = strip_ansi(lines[i])
                if (matches_test(line, class, method)) {
                    print_block(test, i)
                }
            }
        }
    }' "$merged" >> "$out"

    grep -q '^--- correlated with ' "$out"
}

write_karaf_triage_summary() {
    local merged="$1"
    local errors_log="$2"
    local unexpected_log="$3"
    local correlation_log="$4"
    local index_tsv="$5"
    local out="$6"
    local total merged_bytes error_blocks unexpected_blocks correlation_blocks failed_count

    total="$(wc -l < "$merged" | tr -d ' ')"
    merged_bytes="$(wc -c < "$merged" | tr -d ' ')"
    error_blocks="$(grep -c '^--- block ' "$errors_log" 2>/dev/null || echo 0)"
    unexpected_blocks="$(grep -cE '^--- (block|correlated with) ' "$unexpected_log" 2>/dev/null || echo 0)"
    correlation_blocks=0
    if [ -f "$correlation_log" ]; then
        correlation_blocks="$(grep -c '^--- correlated with ' "$correlation_log" 2>/dev/null || echo 0)"
    fi
    failed_count=0
    if [ -f "$(staging_path "$KARAF_FAILED_TESTS_REL")" ]; then
        failed_count="$(wc -l < "$(staging_path "$KARAF_FAILED_TESTS_REL")" | tr -d ' ')"
    fi

    {
        echo "# Karaf triage summary (read this before deep log diving)"
        echo "# Generated: $(it_utc_now)"
        echo
        echo "## Log volume"
        echo "merged.lines=$total"
        echo "merged.bytes=$merged_bytes"
        echo "context.policy=${KARAF_MATCH_CONTEXT_BEFORE}+${KARAF_MATCH_CONTEXT_AFTER} lines, stack extension up to ${KARAF_STACK_MAX_LINES} lines"
        echo "recent.excerpt.lines=$(wc -l < "$(dirname "$out")/$KARAF_RECENT_LOG" 2>/dev/null | tr -d ' ')"
        echo
        echo "## Mined artifacts (priority order for LLM)"
        local n=1
        echo "$n. $KARAF_TRIAGE_SUMMARY (this file)"
        n=$((n + 1))
        if [ "$failed_count" -gt 0 ]; then
            echo "$n. $KARAF_FAILURE_CORRELATION_LOG — excerpts near $failed_count failing test(s)"
            n=$((n + 1))
        fi
        echo "$n. $KARAF_UNEXPECTED_LOG — errors/warnings not matching expected hardening patterns ($unexpected_blocks blocks)"
        n=$((n + 1))
        echo "$n. $KARAF_EXCEPTION_INDEX — top recurring exception/error messages"
        n=$((n + 1))
        echo "$n. $KARAF_ERRORS_LOG — merged error/warn blocks with full stack traces ($error_blocks blocks)"
        n=$((n + 1))
        echo "$n. $KARAF_RECENT_LOG — recent/full log tail for timing context"
        echo
        echo "## Global ignores (same as LogChecker fast paths)"
        echo "- WARN from BundleWatcher (bundle not active during startup)"
        echo "- Karaf JaxbUtil deprecated features.xml namespace warning"
        echo
        echo "## Top recurring signals"
        if [ -f "$index_tsv" ]; then
            tail -n +2 "$index_tsv" | head -15 | while IFS=$'\t' read -r rank count first_line sample; do
                echo "- [$count x, first@$first_line] $sample"
            done
        else
            echo "(none)"
        fi
        echo
        echo "## Workflow"
        echo "1. Confirm failures in failsafe-reports/ and failed-tests.txt ($failed_count listed)"
        echo "2. Read failure correlation excerpts for server-side context"
        echo "3. Use unexpected candidates for novel errors; cross-check expected-karaf-log-patterns.txt"
    } > "$out"
}

filter_unexpected_karaf_blocks() {
    local filtered_log="$1"
    local out="$2"
    : > "$out"

    local block=""
    local block_has_unexpected=0
    local line

    flush_block() {
        if [ -n "$block" ] && [ "$block_has_unexpected" -eq 1 ]; then
            printf '%s\n' "$block" >> "$out"
        fi
        block=""
        block_has_unexpected=0
    }

    while IFS= read -r line || [ -n "$line" ]; do
        if is_karaf_block_header "$line"; then
            flush_block
            block="$line"
            continue
        fi
        if [ -z "$block" ]; then
            continue
        fi
        if [ -z "$line" ] && [ -n "$block" ]; then
            block="$block"$'\n'
            continue
        fi
        block="$block"$'\n'"$line"
        if karaf_line_is_actionable_trigger "$line"; then
            block_has_unexpected=1
        fi
    done < "$filtered_log"
    flush_block
}

run_karaf_triage_step() {
    local spinner_msg="$1"
    local rel_path="$2"
    local success_msg="$3"
    shift 3

    ui_spinner_run "$spinner_msg" "$@"
    register_staged_file "$rel_path" "$success_msg"
}

process_karaf_log_dir() {
    local log_dir="$1"
    local rel base_dir dest_dir merged_tmp
    local context_label segment_count segment_summary recent_lines
    local errors_path unexpected_path index_path correlation_path summary_path failed_path
    local seg name

    rel="${log_dir#"$TARGET_DIR"/}"
    base_dir="$rel"
    dest_dir="$(staging_path "$base_dir")"
    mkdir -p "$dest_dir"

    segment_count="$(count_karaf_log_segments "$log_dir")"
    [ "$segment_count" -gt 0 ] || return

    segment_summary="$(karaf_segment_summary "$segment_count")"
    context_label="${KARAF_MATCH_CONTEXT_BEFORE}+${KARAF_MATCH_CONTEXT_AFTER} (+stack≤${KARAF_STACK_MAX_LINES})"
    errors_path="$(karaf_staged_path "$base_dir" "$KARAF_ERRORS_LOG")"
    unexpected_path="$(karaf_staged_path "$base_dir" "$KARAF_UNEXPECTED_LOG")"
    index_path="$(karaf_staged_path "$base_dir" "$KARAF_EXCEPTION_INDEX")"
    correlation_path="$(karaf_staged_path "$base_dir" "$KARAF_FAILURE_CORRELATION_LOG")"
    summary_path="$(karaf_staged_path "$base_dir" "$KARAF_TRIAGE_SUMMARY")"
    failed_path="$(staging_path "$KARAF_FAILED_TESTS_REL")"

    if [ "$segment_count" -gt 1 ]; then
        write_karaf_segments_index "$log_dir" "$base_dir"
    fi

    if [ "$FULL_KARAF" = true ]; then
        while IFS= read -r seg; do
            [ -n "$seg" ] || continue
            name="$(basename "$seg")"
            cp "$seg" "$dest_dir/$name"
            log_staged_file "$base_dir/$name" "Added full $seg"
        done < <(list_karaf_log_segments "$log_dir")
    fi

    merged_tmp="$(mktemp "${TMPDIR:-/tmp}/karaf-merged.XXXXXX")"
    merge_karaf_log_segments "$log_dir" "$merged_tmp"

    write_karaf_recent_excerpt "$merged_tmp" "$dest_dir/$KARAF_RECENT_LOG"
    recent_lines="$(wc -l < "$dest_dir/$KARAF_RECENT_LOG" | tr -d ' ')"
    register_staged_file "$base_dir/$KARAF_RECENT_LOG" \
        "Added karaf excerpt ($recent_lines lines, max $KARAF_TAIL_MAX_LINES) from $segment_summary under $log_dir"

    if ! run_karaf_triage_step \
        "Mining Karaf errors (merged blocks, full stacks)..." \
        "$base_dir/$KARAF_ERRORS_LOG" \
        "Added merged error/warn blocks ($context_label) from $segment_summary under $log_dir" \
        extract_karaf_errors_with_context "$merged_tmp" "$errors_path"; then
        rm -f "$merged_tmp"
        return
    fi

    run_karaf_triage_step \
        "Building exception index..." \
        "$base_dir/$KARAF_EXCEPTION_INDEX" \
        "Added recurring exception/error index from $segment_summary under $log_dir" \
        write_karaf_exception_index "$merged_tmp" "$index_path"

    if ! run_karaf_triage_step \
        "Filtering expected hardening noise..." \
        "$base_dir/$KARAF_UNEXPECTED_LOG" \
        "Added unexpected-only karaf candidates from $segment_summary under $log_dir" \
        filter_unexpected_karaf_blocks "$errors_path" "$unexpected_path"; then
        ui_detail "All filtered karaf errors/warnings match expected hardening patterns"
    fi

    if write_karaf_failure_correlation "$merged_tmp" "$failed_path" "$correlation_path"; then
        register_staged_file "$base_dir/$KARAF_FAILURE_CORRELATION_LOG" \
            "Added Karaf excerpts correlated with failing tests"
    else
        ui_detail "Skipped $KARAF_FAILURE_CORRELATION_LOG (no failed-tests.txt or no anchors)"
    fi

    write_karaf_triage_summary "$merged_tmp" "$errors_path" "$unexpected_path" \
        "$correlation_path" "$index_path" "$summary_path"
    register_staged_file "$base_dir/$KARAF_TRIAGE_SUMMARY" \
        "Added Karaf triage summary (LLM entry point for log analysis)"

    rm -f "$merged_tmp"
    mark_included
}

archive_karaf_logs() {
    local log_dir found=0

    while IFS= read -r log_dir; do
        [ -n "$log_dir" ] || continue
        if ! karaf_log_dir_has_segments "$log_dir"; then
            continue
        fi
        found=1
        process_karaf_log_dir "$log_dir"
    done < <(
        find "$TARGET_DIR/exam" -type f \( -name "$KARAF_PRIMARY_LOG" -o -name "$KARAF_PRIMARY_LOG".'[0-9]*' \) \
            -path '*/data/log/*' -print 2>/dev/null \
            | sed 's|/[^/]*$||' \
            | sort -u
    )

    if [ "$found" -eq 0 ]; then
        echo "  (no target/exam/*/data/log/karaf.log or karaf.log.N found)" >> "$MANIFEST"
        ui_warn "No Karaf log segments under $TARGET_DIR/exam"
    fi
}
