#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

###
POST http://{{host}}:{{port}}/cxs/profiles/
Authorization: Basic {{authToken}}
Content-Type: application/json

{
  "itemId": "{{profileId}}",
  "itemType": "profile",
  "version": null,
  "properties": {
    "firstName": "John",
    "lastName": "Smith",
    "phoneNumber": null,
    "birthDay": null,
    "interests": {
      "interestName1": 1.0,
      "interestName2": 0.5,
      "interestName3": 0.7
    },
    "simple_Address": {
      "streetName": "Street Name",
      "postalCode": "000000",
      "user_details": {
         "nikname": "superman",
         "workgroup": {
            "workgroup_name": "Test workgroup"
         }
      }
    }
  },
  "systemProperties": {},
  "segments": [],
  "scores": {},
  "mergedWith": null,
  "consents": {
      "digitall/newsletter1": {
            "scope": "digitall",
            "typeIdentifier": "newsletter1",
            "status": "GRANTED",
            "statusDate": "2019-05-15T14:47:28Z",
            "revokeDate": "2021-05-14T14:47:28Z"
        }
  }
}

###
