//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
=== Getting started with Unomi

We will first get you up and running with an example. We will then lift the corner of the cover somewhat and explain
in greater details what just happened.

==== Prerequisites

This document assumes working knowledge of https://git-scm.com/[git] to be able to retrieve the code for Unomi and the example.
Additionally, you will require a working Java 17 or above install. Refer to http://www.oracle.com/technetwork/java/javase/[http://www.oracle.com/technetwork/java/javase/] for details on how to download and install Java SE 17 or greater.

===== JDK compatibility

Starting with Java 9, Oracle made some big changes to the Java platform releases. This is why Apache Unomi is focused on
supporting the Long Term Supported versions of the JDK, currently version 17. We do not test with intermediate
versions so they may or may not work properly. Currently the most tested version is version 17.

Also, as there are new licensing restrictions on JDKs provided by Oracle for production usages, Apache Unomi has also
added support for OpenJDK builds. Other JDK distributions might also work but are not regularly tested so you should use
them at your own risks.

===== Search Engine Compatibility

Apache Unomi supports two search engine backends:

* *ElasticSearch*: Version 7.17.5 is supported starting with Unomi 2.0.0
* *OpenSearch*: Version 2.18.0 is supported

It is highly recommended to use the versions specified in the documentation. When in doubt, consult the Apache Unomi community
for the latest compatibility information.

Note for OpenSearch users:
- Security is enabled by default and requires SSL/TLS
- Default admin credentials are required (username: admin)
- The initial admin password can be configured via environment variable

==== Running Unomi

===== Start Unomi

Start Unomi according to the <<Five Minutes QuickStart,quick start with docker>> or by compiling using the
<<Building,building instructions>>. Once you have Karaf running, you should wait until you see the following messages on the Karaf console:

[source]
----
Initializing user list service endpoint...
Initializing geonames service endpoint...
Initializing segment service endpoint...
Initializing scoring service endpoint...
Initializing campaigns service endpoint...
Initializing rule service endpoint...
Initializing profile service endpoint...
Initializing cluster service endpoint...
----

This indicates that all the Unomi services are started and ready to react to requests. You can then:

1. Access the RESTful services list: `http://localhost:8181/cxs`
2. Retrieve an initial context: `http://localhost:8181/cxs/context.json`
3. View the introduction page: `http://localhost:8181`

Also now that your service is up and running you can go look at the
<<Request examples,request examples>> to learn basic
requests you can do once your server is up and running.
