//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
==== Web Tracker

This extension is providing the web tracker to start collecting visitors data on your website.
The tracker is implemented as an integration of https://github.com/segmentio/analytics.js[analytics.js] for Unomi.

===== Getting started

Extension can be tested at : `http://localhost:8181/tracker/index.html`

In your page include unomiOptions and include code snippet from `snippet.min.js` :

[source]
----
<script type="text/javascript">
        var unomiOption = {
            scope: 'realEstateManager',
            url: 'http://localhost:8181'
        };
        window.unomiTracker||(window.unomiTracker={}),function(){function e(e){for(unomiTracker.initialize({"Apache Unomi":unomiOption});n.length>0;){var r=n.shift(),t=r.shift();unomiTracker[t]&&unomiTracker[t].apply(unomiTracker,r)}}for(var n=[],r=["trackSubmit","trackClick","trackLink","trackForm","initialize","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on","personalize"],t=0;t<r.length;t++){var i=r[t];window.unomiTracker[i]=function(e){return function(){var r=Array.prototype.slice.call(arguments);return r.unshift(e),n.push(r),window.unomiTracker}}(i)}unomiTracker.load=function(){var n=document.createElement("script");n.type="text/javascript",n.async=!0,n.src=unomiOption.url+"/tracker/unomi-tracker.min.js",n.addEventListener?n.addEventListener("load",function(n){"function"==typeof e&&e(n)},!1):n.onreadystatechange=function(){"complete"!==this.readyState&&"loaded"!==this.readyState||e(window.event)};var r=document.getElementsByTagName("script")[0];r.parentNode.insertBefore(n,r)},document.addEventListener("DOMContentLoaded",unomiTracker.load),unomiTracker.page()}();
</script>
----

`window.unomiTracker` can be used to send additional events when needed.

Check analytics.js API https://segment.com/docs/sources/website/analytics.js/[here].
All methods can be used on `unomiTracker` object, although not all event types are supported by Unomi intergation.

===== How to contribute

The source code is in the folder javascript with a package.json, the file to update is `analytics.js-integration-apache-unomi.js` apply your modification in this file then use the command `yarn build` to compile a new JS file.
Then you can use the test page to try your changes `http://localhost:8181/tracker/index.html`.

===== Tracking page views

By default the script will track page views, but maybe you want to take control over this mechanism of add page views
to a single page application. In order to generate a page view programmatically from Javascript you can use code similar
to this :

[source]
----
    <script type="text/javascript">
        // This is an example of how to provide more details page properties to the view event. This can be useful
        // in the case of an SPA that wants to provide information about a view that has metadata such as categories,
        // tags or interests.
        path = location.pathname + location.hash;
        properties = {
            path: path,
            pageInfo: {
                destinationURL: location.href,
                tags : [ "tag1", "tag2", "tag3"],
                categories : ["category1", "category2", "category3"],
                language : "en"
            },
            interests : {
                "interest1" : 1,
                "interest2" : 2,
                "interest3" : 3
            }
        };
        console.log(properties);
        // this will trigger a second page view for the same page (the first page view is in the tracker snippet).
        window.unomiTracker.page(properties);
    </script>
----

Here is a more detail view of what you may include in the pageInfo object :

.PageInfo Properties
|===
|Name|Description

|pageID
|A unique identifier in string format for the page. Default value : page path

|pageName
|A user-displayed name for the page. Default value : page title

|pagePath
|The path of the page, stored by Unomi. This value should be the same as the one passed in the `page` property of the
object passed to the unomiTracker call. Default value : page path

|destinationURL
|The full URL for the page view. This doesn't have to be a real existing URL it could be an internal SPA route. Default value : page URL

|referringURL
|The referringURL also known as the previous URL of the page/screen viewed. Default value : page referrer URL

|language
|An identifier (usually a locale for such as en_US or fr_CH) for the language

|tags
|A String array of tag identifiers. For example `['tag1', 'tag2', 'tag3']`

|categories
|A String array of category identifiers. For example `['category1', 'category2', 'category3']`

|===

The `interests` object is basically list of interests with "weights" attached to them. These interests will be accumulated
in Apache Unomi on profiles to indicate growing interest over time for specific topics. These are freely defined and
will be accepted by Apache Unomi without needing to declare them previously anywhere (the same is true for tags and
categories).