//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
=== What's new in Apache Unomi 3.0

Apache Unomi 3 is a new release focused on integrations of the client to support elasticsearch version 9.
It also include the upgrade of the Karaf version.

==== Elasticsearch client upgrade

The official client for Elasticsearch has been added to Apache Unomi in version 3.0 in order to replace the old rest-client which
is not supported anymore.

The documentation of the client can be found here: https://www.elastic.co/docs/reference/elasticsearch/clients/java

==== Karaf upgrade

The Karaf version has been upgraded from 4.2.15 to 4.4.8 in order to support the latest versions of the dependencies.
This upgrade also brings support for Java 17.
