//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
=== What's new in Apache Unomi 3.0

Apache Unomi 3 is a new release focused on integrations of the client to support elasticsearch version 9.
It also include the upgrade of the Karaf version.

==== Elasticsearch client upgrade

The official client for Elasticsearch has been added to Apache Unomi in version 3.0 in order to replace the old rest-client which
is not supported anymore.

The documentation of the client can be found here: https://www.elastic.co/docs/reference/elasticsearch/clients/java

===  Elasticsearch 7 data migration

A procedure to migrate your data from Elasticsearch 7 to Elasticsearch 9 can be found in the <<Migrate from Elasticsearch 7 to Elasticsearch 9>> section

=== Karaf upgrade

The Karaf version has been upgraded from 4.2.15 to 4.4.8 in order to support the latest versions of the dependencies.
This upgrade also brings support for Java 17.

==== OpenSearch Support

Starting with version 3.1.0, Apache Unomi now officially supports OpenSearch 3 as an alternative to Elasticsearch. This addition gives users more flexibility in choosing their search engine backend. Key features include:

- Full support for OpenSearch 3
- Seamless integration with existing Unomi features
- Support for security features enabled by default in OpenSearch
- Compatible with both standalone and Docker deployments

===== Configuration Options

Users can choose between ElasticSearch and OpenSearch through various configuration methods:

1. Using configuration properties
2. Using Maven profiles during build
3. Using Docker environment variables

For detailed configuration instructions, see the <<Configuration,configuration section>>.

===== Security Considerations

When using OpenSearch:
- Security is enabled by default and requires SSL/TLS
- Default admin credentials are required
- The initial admin password can be configured via environment variables

===== Migration Notes

For users wanting to migrate from ElasticSearch to OpenSearch:
- Data migration requires a full cluster shutdown
- All existing features, including the flattened field type, are supported
- Existing queries and aggregations work seamlessly with both backends

For detailed migration instructions, refer to the <<Migrations,migration guide>>.
