//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
=== Writing Plugins

Apache Unomi is architected to be extensible through plugins. However, it's important to note that plugins are only necessary when custom Java logic is required. Most common needs and use cases can now be covered using:

* Groovy actions (for custom action logic without deployment)
* Complex condition trees (for sophisticated matching logic)
* Rules (for defining business logic and automation)
* Apache Unomi's REST API (for configuration and management)

These built-in features allow you to implement most functionality without deploying any code, making the system more maintainable and reducing development overhead. You should only consider developing a plugin when you need to:

* Implement custom Java-based query builders for search engine integration
* Add new core system functionality that requires deep integration
* Optimize performance-critical operations with compiled code
* Integrate with external systems requiring complex Java libraries

=== Types vs. instances

Several extension points in Unomi rely on the concept of type: a plugin defines a prototype for what the actual
items will be once parameterized with values known only at runtime. This is similar to the concept of classes in
object-oriented programming: types define classes, providing the expected structure and which fields are expected to
be provided at runtime, that are then instantiated when needed with actual values.

So for example we have the following types vs instances:

- ConditionTypes vs Conditions
- ActionTypes vs Actions
- PropertyTypes vs Properties (for profiles and sessions)

=== Plugin structure

Being built on top of Apache Karaf, Unomi leverages OSGi to support plugins. A Unomi plugin is, thus, an OSGi
bundle specifying some specific metadata to tell Unomi the kind of entities it provides. A plugin can provide the
following entities to extend Unomi, each with its associated definition (as a JSON file), located in a specific spot
within the `META-INF/cxs/` directory of the bundle JAR file:

|====
|Entity |Location in `cxs` directory

|ActionType |actions
|ConditionType |conditions
|Persona |personas
|PropertyMergeStrategyType |mergers
|PropertyType |properties then profiles or sessions subdirectory then `&lt;category name&gt;` directory
|Rule |rules
|Scoring |scorings
|Segment |segments
|ValueType |values
|====

http://aries.apache.org/modules/blueprint.html[Blueprint] is used to declare what the plugin provides and inject
any required dependency. The Blueprint file is located, as usual, at `OSGI-INF/blueprint/blueprint.xml` in the bundle JAR file.

=== Search Engine Specific Implementations

When implementing plugins that need to interact with the search engine layer (ElasticSearch or OpenSearch), special consideration must be taken to ensure compatibility and proper deployment.

==== Search Engine Specific Bundles

For plugins that provide search query builder implementations, you should structure your plugin with three bundles:
1. A common bundle for shared code and resources
2. An ElasticSearch-specific implementation bundle
3. An OpenSearch-specific implementation bundle

Example structure:
```
my-plugin/
├── common/
│   ├── src/main/java/.../
│   │   ├── model/
│   │   │   └── MyCustomCondition.java
│   │   └── services/
│   │       └── MyCustomService.java
│   ├── src/main/resources/META-INF/cxs/
│   │   ├── conditions/
│   │   │   └── my-custom-condition.json
│   │   └── actions/
│   │       └── my-custom-action.json
│   └── pom.xml
├── elasticsearch/
│   ├── src/main/java/.../
│   │   └── impl/
│   │       └── MyElasticSearchQueryBuilder.java
│   ├── src/main/resources/META-INF/cxs/
│   │   └── mappings/
│   │       └── my-index-mapping.json
│   └── pom.xml
├── opensearch/
│   ├── src/main/java/.../
│   │   └── impl/
│   │       └── MyOpenSearchQueryBuilder.java
│   ├── src/main/resources/META-INF/cxs/
│   │   └── mappings/
│   │       └── my-index-mapping.json
│   └── pom.xml
└── pom.xml
```

Example POM dependencies:

Common Bundle (my-plugin-common):
[source,xml]
----
<dependencies>
    <dependency>
        <groupId>org.apache.unomi</groupId>
        <artifactId>unomi-api</artifactId>
        <version>${unomi.version}</version>
        <scope>provided</scope>
    </dependency>
</dependencies>
----

ElasticSearch Bundle (my-plugin-elasticsearch):
[source,xml]
----
<dependencies>
    <dependency>
        <groupId>my.group.id</groupId>
        <artifactId>my-plugin-common</artifactId>
        <version>${project.version}</version>
    </dependency>
    <dependency>
        <groupId>org.apache.unomi</groupId>
        <artifactId>unomi-persistence-elasticsearch-core</artifactId>
        <version>${unomi.version}</version>
        <scope>provided</scope>
    </dependency>
</dependencies>
----

OpenSearch Bundle (my-plugin-opensearch):
[source,xml]
----
<dependencies>
    <dependency>
        <groupId>my.group.id</groupId>
        <artifactId>my-plugin-common</artifactId>
        <version>${project.version}</version>
    </dependency>
    <dependency>
        <groupId>org.apache.unomi</groupId>
        <artifactId>unomi-persistence-opensearch-core</artifactId>
        <version>${unomi.version}</version>
        <scope>provided</scope>
    </dependency>
</dependencies>
----

==== Configuration and Deployment

Administrators can control which search engine implementation to use through the `org.apache.unomi.start.cfg` configuration file. This file determines which features (including your plugin's bundles) are deployed based on the chosen search engine:

[source]
----
startFeatures = [
    "elasticsearch=unomi-persistence-elasticsearch,my-plugin-elasticsearch,unomi-services,...",
    "opensearch=unomi-persistence-opensearch,my-plugin-opensearch,unomi-services,..."
]
----

==== Custom Plugins

The plugin otherwise follows a regular maven project layout and should depend on the Unomi API maven artifact:

[source,xml]
----
<dependency>
    <groupId>org.apache.unomi</groupId>
    <artifactId>unomi-api</artifactId>
    <version>...</version>
</dependency>
----

Some plugins consists only of JSON definitions that are used to instantiate the appropriate structures at runtime
while some more involved plugins provide code that extends Unomi in deeper ways.

In both cases, plugins can provide more that one type of extension. For example, a plugin could provide both `ActionType`s and `ConditionType`s.

=== Extension points

In this section the value types that may be used as extension points are presented. Examples of these types will be
given in the next section with more details.

==== ActionType

`ActionType`s define new actions that can be used as consequences of Rules being triggered. When a rule triggers, it
creates new actions based on the event data and the rule internal processes, providing values for parameters defined
in the associated `ActionType`. Example actions include: “Set user property x to value y” or “Send a message to service x”.

==== ConditionType

`ConditionType`s define new conditions that can be applied to items (for example to decide whether a rule needs to be
triggered or if a profile is considered as taking part in a campaign) or to perform queries against the stored Unomi
data. They may be implemented in Java when attempting to define a particularly complex test or one that can better be
optimized by coding it. They may also be defined as combination of other conditions. A simple condition could be:
“User is male”, while a more generic condition with parameters may test whether a given property has a specific value:
“User property x has value y”.

==== Persona

A persona is a "virtual" profile used to represent categories of profiles, and may also be used to test how a
personalized experience would look like using this virtual profile. A persona can define predefined properties and
sessions. Persona definition make it possible to “emulate” a certain type of profile, e.g : US visitor, non-US visitor, etc.

==== PropertyMergeStrategyType

A strategy to resolve how to merge properties when merging profile together.

==== PropertyType

Definition for a profile or session property, specifying how possible values are constrained, if the value is
multi-valued (a vector of values as opposed to a scalar value). `PropertyType`s can also be categorized using
systemTags or file system structure, using sub-directories to organize definition files.

==== Rule

`Rule`s are conditional sets of actions to be executed in response to incoming events. Triggering of rules is guarded
by a condition: the rule is only triggered if the associated condition is satisfied. That condition can test the
event itself, but also the profile or the session. Once a rule triggers, a list of actions can be performed as
consequences. Also, when rules trigger, a specific event is raised so that other parts of Unomi can react accordingly.

==== Scoring

`Scoring`s are set of conditions associated with a value to assign to profiles when matching so that the associated
users can be scored along that dimension. Each scoring element is evaluated and matching profiles' scores are
incremented with the associated value.

==== Segments

`Segment`s represent dynamically evaluated groups of similar profiles in order to categorize the associated users.
To be considered part of a given segment, users must satisfies the segment’s condition. If they match, users are
automatically added to the segment. Similarly, if at any given point during, they cease to satisfy the segment’s
condition, they are automatically removed from it.

==== Tag

`Tag`s are simple labels that are used to classify all other objects inside Unomi.

==== ValueType

Definition for values that can be assigned to properties ("primitive" types).

=== Custom plugins

Apache Unomi is a pluggeable server that may be extended in many ways. This document assumes you are familiar with the
<<Data Model Overview,Apache Unomi Data Model>> . This document is mostly a reference document on the different things that may
be used inside an extension. If you are looking for complete samples, please see the <<Samples,samples page>>.

==== Creating a plugin

An plugin is simply a Maven project, with a Maven pom that looks like this:

[source]
----
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>org.apache.unomi</groupId>
        <artifactId>unomi-plugins</artifactId>
        <version>${project.version}</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>

    <artifactId>unomi-plugin-example</artifactId>
    <name>Apache Unomi :: Plugins :: Example</name>
    <description>A sample example of a Unomi plugin</description>
    <version>${project.version}</version>
    <packaging>bundle</packaging>

    <dependencies>
        <!-- This dependency is not required but generally used in plugins -->
        <dependency>
            <groupId>org.apache.unomi</groupId>
            <artifactId>unomi-api</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <extensions>true</extensions>
                <configuration>
                    <instructions>
                        <Embed-Dependency>*;scope=compile|runtime</Embed-Dependency>
                        <Import-Package>
                            sun.misc;resolution:=optional,
                            *
                        </Import-Package>
                    </instructions>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
----

A plugin may contain many different kinds of Apache Unomi objects, as well as custom OSGi services or anything that
is needed to build your application.

==== Deployment and custom definition

When you deploy a custom bundle with a custom definition (see "Predefined xxx" chapters under) for the first time, the
definition will automatically be deployed at your bundle start event *if it does not exist*.
After that if you redeploy the same bundle, the definition will not be redeployed, but you can redeploy it manually
using the command `unomi:deploy-definition &lt;bundleId&gt; &lt;fileName&gt;` If you need to modify an existing
definition when deploying the module, see <<Migration patches>>.

==== Predefined segments

You may provide pre-defined segments by simply adding a JSON file in the src/main/resources/META-INF/cxs/segments directory of
your Maven project. Here is an example of a pre-defined segment:

[source]
----
{
  "metadata": {
    "id": "leads",
    "name": "Leads",
    "scope": "systemscope",
    "description": "You can customize the list below by editing the leads segment.",
    "readOnly":true
  },
  "condition": {
    "parameterValues": {
      "subConditions": [
        {
          "parameterValues": {
            "propertyName": "properties.leadAssignedTo",
            "comparisonOperator": "exists"
          },
          "type": "profilePropertyCondition"
        }
      ],
      "operator" : "and"
    },
    "type": "booleanCondition"
  }
}
----

Basically this segment uses a condition to test if the profile has a property `leadAssignedTo` that exists. All profiles
that match this condition will be part of the pre-defined segment.

==== Predefined rules

You may provide pre-defined rules by simply adding a JSON file in the src/main/resources/META-INF/cxs/rules directory of
your Maven project. Here is an example of a pre-defined rule:

[source]
----
{
    "metadata" : {
        "id": "evaluateProfileSegments",
        "name": "Evaluate segments",
        "description" : "Evaluate segments when a profile is modified",
        "readOnly":true
    },

    "condition" : {
        "type": "profileUpdatedEventCondition",
        "parameterValues": {
        }
    },

    "actions" : [
        {
            "type": "evaluateProfileSegmentsAction",
            "parameterValues": {
            }
        }
    ]

}
----

In this example we provide a rule that will execute when a predefined composed condition of type
"profileUpdatedEventCondition" is received. See below to see how predefined composed conditions are declared.
Once the condition is matched, the actions will be executed in sequence. In this example there is only a single
action of type "evaluateProfileSegmentsAction" that is defined so it will be executed by Apache Unomi's rule engine.
You can also see below how custom actions may be defined.

==== Predefined properties

By default Apache Unomi comes with a set of pre-defined properties, but in many cases it is useful to add additional
predefined property definitions. You can create property definitions for session or profile properties by creating them
in different directories.

For session properties you must create a JSON file in the following directory in your Maven project:

[source]
----
src/main/resources/META-INF/cxs/properties/sessions
----

For profile properties you must create the JSON file inside the directory in your Maven project:

[source]
----
src/main/resources/META-INF/cxs/properties/profiles
----

Here is an example of a property definition JSON file

[source]
----
{
    "metadata": {
        "id": "city",
        "name": "City",
        "systemTags": ["properties", "profileProperties", "contactProfileProperties"]
    },
    "type": "string",
    "defaultValue": "",
    "automaticMappingsFrom": [ ],
    "rank": "304.0"
}
----

==== Predefined child conditions

You can define new predefined conditions that are actually conditions inheriting from a parent condition and setting
pre-defined parameter values. You can do this by creating a JSON file in:

[source]
----
src/main/resources/META-INF/cxs/conditions
----

Here is an example of a JSON file that defines a profileUpdateEventCondition that inherits from a parent condition of
type eventTypeCondition.

[source]
----
{
  "metadata": {
    "id": "profileUpdatedEventCondition",
    "name": "profileUpdatedEventCondition",
    "description": "",
    "systemTags": [
      "event",
      "eventCondition"
    ],
    "readOnly": true
  },
  "parentCondition": {
    "type": "eventTypeCondition",
    "parameterValues": {
      "eventTypeId": "profileUpdated"
    }
  },

  "parameters": [
  ]
}
----

==== Predefined personas

Personas may also be pre-defined by creating JSON files in the following directory:

[source]
----
src/main/resources/META-INF/cxs/personas
----

Here is an example of a persona definition JSON file:

[source]
----
{
    "persona": {
        "itemId": "usVisitor",
        "properties": {
            "description": "Represents a visitor browsing from inside the continental US",
            "firstName": "U.S.",
            "lastName": "Visitor"
        },
        "segments": []
    },
    "sessions": [
        {
            "itemId": "aa3b04bd-8f4d-4a07-8e96-d33ffa04d3d9",
            "profileId": "usVisitor",
            "properties": {
                "operatingSystemName": "OS X 10.9 Mavericks",
                "sessionCountryName": "United States",
                "location": {
                    "lat":37.422,
                    "lon":-122.084058
                },
                "userAgentVersion": "37.0.2062.120",
                "sessionCountryCode": "US",
                "deviceCategory": "Personal computer",
                "operatingSystemFamily": "OS X",
                "userAgentName": "Chrome",
                "sessionCity": "Mountain View"
            },
            "timeStamp": "2014-09-18T11:40:54Z",
            "lastEventDate": "2014-09-18T11:40:59Z",
            "duration": 4790
        }
    ]
}
----

You can see that it's also possible to define sessions for personas.

==== Custom action types

Custom action types are a powerful way to integrate with external systems by being able to define custom logic that will
be executed by an Apache Unomi rule. An action type is defined by a JSON file created in the following directory:

[source]
----
src/main/resources/META-INF/cxs/actions
----

Here is an example of a JSON action definition:

[source]
----
{
  "metadata": {
    "id": "addToListsAction",
    "name": "addToListsAction",
    "description": "",
    "systemTags": [
      "demographic",
      "availableToEndUser"
    ],
    "readOnly": true
  },
  "actionExecutor": "addToLists",
  "parameters": [
    {
      "id": "listIdentifiers",
      "type": "string",
      "multivalued": true
    }
  ]
}
----

The `actionExecutor` identifier refers to a service property that is defined in the OSGi Blueprint service registration.
Note that any OSGi service registration may be used, but in these examples we use OSGi Blueprint. The definition for the
above JSON file will be found in a file called `src/main/resources/OSGI-INF/blueprint/blueprint.xml` with the following
content:

[source]
----
<?xml version="1.0" encoding="UTF-8"?>
<blueprint xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.osgi.org/xmlns/blueprint/v1.0.0"
           xsi:schemaLocation="http://www.osgi.org/xmlns/blueprint/v1.0.0 http://www.osgi.org/xmlns/blueprint/v1.0.0/blueprint.xsd">

    <reference id="profileService" interface="org.apache.unomi.api.services.ProfileService"/>
    <reference id="eventService" interface="org.apache.unomi.api.services.EventService"/>

    <!-- Action executors -->

    <service interface="org.apache.unomi.api.actions.ActionExecutor">
        <service-properties>
            <entry key="actionExecutorId" value="addToLists"/>
        </service-properties>
        <bean class="org.apache.unomi.lists.actions.AddToListsAction">
            <property name="profileService" ref="profileService"/>
            <property name="eventService" ref="eventService"/>
        </bean>
    </service>

</blueprint>
----

You can note here the `actionExecutorId` that corresponds to the `actionExecutor` in the JSON file.

The implementation of the action is available here : https://github.com/apache/unomi/blob/master/extensions/lists-extension/actions/src/main/java/org/apache/unomi/lists/actions/AddToListsAction.java[org.apache.unomi.lists.actions.AddToListsAction]

==== Custom condition types

Custom condition types are different from predefined child conditions because they implement their logic using Java classes.
They are also declared by adding a JSON file into the `conditions` directory:

[source]
----
src/main/resources/META-INF/cxs/conditions
----

Here is an example of JSON custom condition type definition:

[source]
----
{
  "metadata": {
    "id": "matchAllCondition",
    "name": "matchAllCondition",
    "description": "",
    "systemTags": [
      "logical",
      "profileCondition",
      "eventCondition",
      "sessionCondition",
      "sourceEventCondition"
    ],
    "readOnly": true
  },
  "conditionEvaluator": "matchAllConditionEvaluator",
  "queryBuilder": "matchAllConditionQueryBuilder",

  "parameters": [
  ]
}
----

Note the `conditionEvaluator` and the `queryBuilder` values. These reference OSGi service properties that are declared
in an OSGi Blueprint configuration file (other service definitions may also be used such as Declarative Services or even
Java registered services). Here is an example of an OSGi Blueprint definition corresponding to the above JSON condition
type definition file.

[source]
----
src/main/resources/OSGI-INF/blueprint/blueprint.xml

<blueprint xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.osgi.org/xmlns/blueprint/v1.0.0"
           xsi:schemaLocation="http://www.osgi.org/xmlns/blueprint/v1.0.0 http://www.osgi.org/xmlns/blueprint/v1.0.0/blueprint.xsd">

    <service
            interface="org.apache.unomi.persistence.elasticsearch.ConditionESQueryBuilder">
        <service-properties>
            <entry key="queryBuilderId" value="matchAllConditionQueryBuilder"/>
        </service-properties>
        <bean class="conditions.org.apache.unomi.persistence.elasticsearch.MatchAllConditionESQueryBuilder"/>
    </service>

    <service interface="org.apache.unomi.persistence.spi.conditions.ConditionEvaluator">
        <service-properties>
            <entry key="conditionEvaluatorId" value="matchAllConditionEvaluator"/>
        </service-properties>
        <bean class="org.apache.unomi.plugins.baseplugin.conditions.MatchAllConditionEvaluator"/>
    </service>

</blueprint>
----

You can find the implementation of the two classes here :

* https://github.com/apache/unomi/blob/master/plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/conditions/MatchAllConditionESQueryBuilder.java[conditions.org.apache.unomi.persistence.elasticsearch.MatchAllConditionESQueryBuilder]
* https://github.com/apache/unomi/blob/master/plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/conditions/MatchAllConditionEvaluator.java[org.apache.unomi.plugins.baseplugin.conditions.MatchAllConditionEvaluator]

==== Implementation Examples

Here's a complete example of implementing custom query builders for both search engines following Apache Unomi 3.0 best practices:

**ElasticSearch Implementation:**
[source,java]
----
package org.apache.unomi.plugin.elasticsearch;

import co.elastic.clients.elasticsearch._types.query_dsl.Query;
import org.apache.unomi.api.conditions.Condition;
import org.apache.unomi.persistence.elasticsearch.ConditionESQueryBuilder;
import org.apache.unomi.persistence.elasticsearch.ConditionESQueryBuilderDispatcher;

import java.util.Map;

public class MyCustomQueryBuilder implements ConditionESQueryBuilder {
    
    @Override
    public Query buildQuery(Condition condition, Map<String, Object> context, 
                           ConditionESQueryBuilderDispatcher dispatcher) {
        // Get parameters from the condition
        String fieldName = (String) condition.getParameter("fieldName");
        String fieldValue = (String) condition.getParameter("fieldValue");
        
        // Build Elasticsearch-specific query using the new client
        return Query.of(q -> q
            .bool(b -> b
                .must(m -> m
                    .term(t -> t
                        .field(fieldName)
                        .value(v -> v.stringValue(fieldValue))
                    )
                )
            )
        );
    }
    
    @Override
    public long count(Condition condition, Map<String, Object> context, 
                     ConditionESQueryBuilderDispatcher dispatcher) {
        // Implement count logic if needed
        return 0;
    }
}
----

**OpenSearch Implementation:**
[source,java]
----
package org.apache.unomi.plugin.opensearch;

import org.opensearch.client.opensearch._types.query_dsl.Query;
import org.apache.unomi.api.conditions.Condition;
import org.apache.unomi.persistence.opensearch.ConditionOSQueryBuilder;
import org.apache.unomi.persistence.opensearch.ConditionOSQueryBuilderDispatcher;

import java.util.Map;

public class MyCustomQueryBuilder implements ConditionOSQueryBuilder {
    
    @Override
    public Query buildQuery(Condition condition, Map<String, Object> context, 
                           ConditionOSQueryBuilderDispatcher dispatcher) {
        // Get parameters from the condition
        String fieldName = (String) condition.getParameter("fieldName");
        String fieldValue = (String) condition.getParameter("fieldValue");
        
        // Build OpenSearch-specific query
        return Query.of(q -> q
            .bool(b -> b
                .must(m -> m
                    .term(t -> t
                        .field(fieldName)
                        .value(v -> v.stringValue(fieldValue))
                    )
                )
            )
        );
    }
    
    @Override
    public long count(Condition condition, Map<String, Object> context, 
                     ConditionOSQueryBuilderDispatcher dispatcher) {
        // Implement count logic if needed
        return 0;
    }
}
----

**OSGi Service Registration for ElasticSearch** (`elasticsearch-bundle/src/main/resources/OSGI-INF/blueprint/blueprint.xml`):
[source,xml]
----
<blueprint xmlns="http://www.osgi.org/xmlns/blueprint/v1.0.0">
    <!-- Register the query builder with the new naming convention -->
    <service interface="org.apache.unomi.persistence.elasticsearch.ConditionESQueryBuilder">
        <service-properties>
            <entry key="queryBuilderId" value="myCustomQueryBuilder"/>
        </service-properties>
        <bean class="org.apache.unomi.plugin.elasticsearch.MyCustomQueryBuilder"/>
    </service>
</blueprint>
----

**OSGi Service Registration for OpenSearch** (`opensearch-bundle/src/main/resources/OSGI-INF/blueprint/blueprint.xml`):
[source,xml]
----
<blueprint xmlns="http://www.osgi.org/xmlns/blueprint/v1.0.0">
    <!-- Register the query builder with the new naming convention -->
    <service interface="org.apache.unomi.persistence.opensearch.ConditionOSQueryBuilder">
        <service-properties>
            <entry key="queryBuilderId" value="myCustomQueryBuilder"/>
        </service-properties>
        <bean class="org.apache.unomi.plugin.opensearch.MyCustomQueryBuilder"/>
    </service>
</blueprint>
----

**Condition Type Definition** (shared between both implementations):
[source,json]
----
{
  "metadata": {
    "id": "myCustomCondition",
    "name": "My Custom Condition",
    "description": "A custom condition for demonstration purposes",
    "systemTags": ["custom", "condition"],
    "readOnly": false
  },
  "queryBuilder": "myCustomQueryBuilder",
  "parameters": [
    {
      "id": "fieldName",
      "type": "string",
      "multivalued": false
    },
    {
      "id": "fieldValue", 
      "type": "string",
      "multivalued": false
    }
  ]
}
----

==== Project Structure and Packaging

For plugins that support both Elasticsearch and OpenSearch, follow this recommended project structure:

```
my-custom-plugin/
├── pom.xml                          # Parent POM
├── my-custom-plugin-common/         # Shared code and interfaces
│   ├── pom.xml
│   └── src/main/java/
│       └── org/apache/unomi/plugin/
│           └── common/
│               ├── MyCustomConditionType.java
│               └── MyCustomConditionEvaluator.java
├── my-custom-plugin-elasticsearch/  # Elasticsearch-specific implementation
│   ├── pom.xml
│   └── src/main/
│       ├── java/
│       │   └── org/apache/unomi/plugin/elasticsearch/
│       │       └── MyCustomQueryBuilder.java
│       └── resources/
│           └── OSGI-INF/blueprint/
│               └── blueprint.xml
├── my-custom-plugin-opensearch/     # OpenSearch-specific implementation
│   ├── pom.xml
│   └── src/main/
│       ├── java/
│       │   └── org/apache/unomi/plugin/opensearch/
│       │       └── MyCustomQueryBuilder.java
│       └── resources/
│           └── OSGI-INF/blueprint/
│               └── blueprint.xml
└── my-custom-plugin-features/       # Karaf feature definitions
    ├── pom.xml
    └── src/main/resources/
        └── features.xml
```

**Parent POM Configuration:**
[source,xml]
----
<project>
    <groupId>org.apache.unomi.plugins</groupId>
    <artifactId>my-custom-plugin</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    
    <modules>
        <module>my-custom-plugin-common</module>
        <module>my-custom-plugin-elasticsearch</module>
        <module>my-custom-plugin-opensearch</module>
        <module>my-custom-plugin-features</module>
    </modules>
    
    <properties>
        <unomi.version>3.0.0</unomi.version>
    </properties>
</project>
----

**Elasticsearch Bundle POM:**
[source,xml]
----
<project>
    <parent>
        <groupId>org.apache.unomi.plugins</groupId>
        <artifactId>my-custom-plugin</artifactId>
        <version>1.0.0</version>
    </parent>
    
    <artifactId>my-custom-plugin-elasticsearch</artifactId>
    <packaging>bundle</packaging>
    
    <dependencies>
        <dependency>
            <groupId>org.apache.unomi</groupId>
            <artifactId>unomi-api</artifactId>
            <version>${unomi.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.unomi</groupId>
            <artifactId>persistence-elasticsearch-core</artifactId>
            <version>${unomi.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.unomi.plugins</groupId>
            <artifactId>my-custom-plugin-common</artifactId>
            <version>1.0.0</version>
        </dependency>
    </dependencies>
    
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <extensions>true</extensions>
                <configuration>
                    <instructions>
                        <Bundle-SymbolicName>my-custom-plugin-elasticsearch</Bundle-SymbolicName>
                        <Bundle-Name>My Custom Plugin - Elasticsearch</Bundle-Name>
                        <Export-Package>org.apache.unomi.plugin.elasticsearch</Export-Package>
                        <Import-Package>*</Import-Package>
                    </instructions>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
----

**Karaf Feature Definitions:**

`features.xml` (single file with multiple feature definitions):
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<features name="my-custom-plugin" version="1.0.0">
    
    <!-- Elasticsearch feature -->
    <feature name="my-custom-plugin-elasticsearch" version="1.0.0">
        <bundle>mvn:org.apache.unomi.plugins/my-custom-plugin-common/1.0.0</bundle>
        <bundle>mvn:org.apache.unomi.plugins/my-custom-plugin-elasticsearch/1.0.0</bundle>
        <feature>unomi-elasticsearch</feature>
    </feature>
    
    <!-- OpenSearch feature -->
    <feature name="my-custom-plugin-opensearch" version="1.0.0">
        <bundle>mvn:org.apache.unomi.plugins/my-custom-plugin-common/1.0.0</bundle>
        <bundle>mvn:org.apache.unomi.plugins/my-custom-plugin-opensearch/1.0.0</bundle>
        <feature>unomi-opensearch</feature>
    </feature>
</features>
----

==== Best Practices

1. **Naming Conventions**
   - Use generic queryBuilder IDs (e.g., `myCustomQueryBuilder`) instead of search engine-specific ones
   - Follow the new naming convention: remove "ES" references, use "QueryBuilder" suffix
   - Keep the same queryBuilder ID across both implementations for consistency

2. **Code Organization**
   - Keep shared logic in a common module (condition types, evaluators, utilities)
   - Implement search engine specific code only where necessary
   - Use interfaces to define common behavior
   - Minimize code duplication between implementations

3. **OSGi Service Registration**
   - Register services only in the appropriate bundle (Elasticsearch vs OpenSearch)
   - Use the same `queryBuilderId` in service properties for both implementations
   - Ensure proper dependency management to avoid conflicts

4. **Testing Strategy**
   - Create test suites for both implementations
   - Use Docker containers for integration testing:
     ```yaml
     services:
       elasticsearch:
         image: docker.elastic.co/elasticsearch/elasticsearch:9.15.0
       opensearch:
         image: opensearchproject/opensearch:3.0.0
     ```
   - Test with both search engines to ensure compatibility

5. **Deployment Configuration**
   - Package search engine specific code in separate bundles
   - Use a single feature file with multiple feature definitions for better organization
   - Configure the appropriate feature in your deployment based on the selected search engine:
     - For Elasticsearch: `feature:install my-custom-plugin-elasticsearch`
     - For OpenSearch: `feature:install my-custom-plugin-opensearch`
   - Document dependencies and requirements clearly

==== Custom Start Configuration

For production deployments, you can create a custom `org.apache.unomi.start.cfg` file to automatically include your plugin features in the startup configuration. This approach ensures your plugin is automatically deployed when Apache Unomi starts.

**Creating a Custom Start Configuration:**

1. **Create the configuration file** in your deployment directory:
   ```
   etc/org.apache.unomi.start.cfg
   ```

2. **Define your custom configurations** by extending the default ones:

[source,properties]
----
# Custom start configurations that include your plugin features
startFeatures = [ "elasticsearch=unomi-base,unomi-startup,unomi-elasticsearch-core,unomi-persistence-core,unomi-services,unomi-rest-api,unomi-cxs-lists-extension,unomi-cxs-geonames-extension,unomi-cxs-privacy-extension,unomi-elasticsearch-conditions,unomi-plugins-base,unomi-plugins-request,unomi-plugins-mail,unomi-plugins-optimization-test,unomi-shell-dev-commands,unomi-wab,unomi-web-tracker,unomi-healthcheck,unomi-router-karaf-feature,unomi-groovy-actions,unomi-rest-ui,unomi-startup-complete,my-custom-plugin-elasticsearch", \
                  "opensearch=unomi-base,unomi-startup,unomi-opensearch-core,unomi-persistence-core,unomi-services,unomi-rest-api,unomi-cxs-lists-extension,unomi-cxs-geonames-extension,unomi-cxs-privacy-extension,unomi-opensearch-conditions,unomi-plugins-base,unomi-plugins-request,unomi-plugins-mail,unomi-plugins-optimization-test,unomi-shell-dev-commands,unomi-wab,unomi-web-tracker,unomi-healthcheck,unomi-router-karaf-feature,unomi-groovy-actions,unomi-rest-ui,unomi-startup-complete,my-custom-plugin-opensearch" ]
----

**Key Points:**

- **Feature ordering**: Your custom plugin features should be added at the end of the feature list, after the core Apache Unomi features
- **Search engine specific**: Include only the appropriate feature for your selected search engine
- **Dependency management**: Ensure your plugin features are listed after their dependencies (e.g., after `unomi-elasticsearch-core` or `unomi-opensearch-core`)


**Benefits of Custom Start Configuration:**

- **Automatic deployment**: Your plugin is automatically installed when Apache Unomi starts
- **Consistent environments**: Ensures the same features are deployed across all environments
- **Production ready**: No manual feature installation required
- **Version control**: Configuration can be versioned and managed with your deployment

**Note**: For more detailed information about customizing start features configurations, including environment-specific examples, see the <<Customizing Start Features Configuration,Configuration>> section of the documentation.

6. **Migration from Legacy Implementations**
   - **DO NOT** use legacy mappings for custom query builders
   - Rename existing query builders to follow new naming conventions
   - Update condition type definitions to use new queryBuilder IDs
   - Test thoroughly after migration

==== Learning from Core Implementation

You can study the core persistence implementations as references:

1. ElasticSearch Implementation:
   - Location: `persistence-elasticsearch/core`
   - Key classes:
     * ElasticSearchPersistenceServiceImpl
     * ElasticSearchQueryBuilder

2. OpenSearch Implementation:
   - Location: `persistence-opensearch/core`
   - Key classes:
     * OpenSearchPersistenceServiceImpl
     * OpenSearchQueryBuilder

These implementations demonstrate:
- How to handle search engine specific features
- Query building patterns
- Mapping file organization
- Error handling and retry mechanisms
- Connection management
- Security configuration

